config/routes.rb
Rails.application.routes.draw do
  # GETはデータの取得。aタグなどで、画面遷移の際に新しいページを取得する場合はGET。
  # POSTはデータの新規保存。フォーム等で投稿をする場合はPOST。
  # PATCHはデータの更新。
  # 「HTMLメソッド 'URL' => 'コントローラ名#アクション名'」という書き方。
  # rootメソッドを用いた、ルートディレクトリ(/)へのルーティング設定。(top画面をルートパス(最上位階層のURL)に設定している)
  root :to => 'homes#top'

    # resourcesメソッド…ルーティングを一括して自動生成してくれる。
    # この場合、booksコントローラの同じ名前のアクションに紐づく形で、以下のルーティングを自動生成してくれる。
  # resources :books => index,show,new,create,edit,update,destroyの7つのアクションのルーティングをrails側が自動生成してくれる。
  # HTTPメソッドも自動設定してくれるので、いちいちpost、patch、deleteとか記述しなくていい。
  post 'books' => 'books#create'
  get 'books' => 'books#index'
    # 詳細画面(show)はどの投稿データを表示するかを判別するために、投稿データのidもURLに含める。
    # 詳細画面で呼び出される投稿データは、URLの/books/:id内の:idで判別する。 この:idは、アクション内にparams[:id]と記述する事で取得可能。
    # as: 'book'…名前付きルート。ルーティング自体に名前をつけておく事。名前付きルートがあると、その名前をredirect_toやlink_toでも使用可能。
    # as:オプションを追加することで設定が出来る。 ここでは「'books#show'の設定を、bookとして利用できる」の意味。
  get 'books/:id' => 'books#show', as: 'book'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  patch 'books/:id' => 'books#update', as: 'update_book'    # resources :booksで纏めたせいで、名前付きルートupdate_bookが消えててエラーが起きた
  delete 'books/:id' => 'books#destroy', as: 'destroy_book' # resources :booksで纏めたせいで、名前付きルートdestroy_bookが消えててエラーが起きた
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  # バリデーションの設定。←モデルのファイルに設定内容を記述する。
  # validatesで「必須入力」にしたい項目を指定し、入力されたデータのpresence（存在）をチェックする。
  # trueと記述すると、データが存在しなければならないという設定になる。
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  # データの新規作成フォームを作成・表示する役割のアクション
  def new
    # viewへ渡すためのインスタンス変数に空のModelオブジェクトを生成する。
    # このnewはJavaのインスタンス(実体)生成と同じようなもの？モデルBookの実体(オブジェクト)を生成してインスタンス変数@bookに渡してる？
    @book = Book.new
  end

  # データを追加（保存）する役割のアクション
  def create
    # フォームに入力したデータを受け取り、それを元に、新規登録するためのインスタンスを作成。
    # Book(Model)のメソッドであるnewメソッドが呼び出され、引数でbook_paramsメソッドが呼び出されている。
    # book_paramsを引数にする事で絞り込んだデータを受け取り、それを元にnewメソッドでインスタンスを作ってる。
    # ここでやってるのは絞り込んだデータを元にしたインスタンス生成であって保存ではない。book_paramsはデータを絞り込むだけで保存はしない。
    # 何故newアクションを呼び出す必要が？ここのnewは何？
    @book = Book.new(book_params)
    # 上記で生成したインスタンスにsaveメソッド(インスタンスをデータベースに保存するメソッド)を使い、データをデータベースに保存する。
    # バリデーションの結果を、コントローラで検出できるようにする。(if文を用いる)
    # book.rb(モデルファイル)にバリデーションチェックを設定しているため、saveメソッドが走った際、trueかfalseが返ってくる。
    # 対象のカラムにデータが入力されていた場合はtrueが返ってくる。この場合、次に表示したいページにリダイレクトさせる。
    # 対象のカラムにデータが入力されていなかった場合はfalseが返ってくる。この場合、新規投稿ページを再表示させる。
    if @book.save
      # 投稿に成功した場合のフラッシュメッセージ
      # flashオブジェクトのキーである[:notice]に表示したいメッセージをvalueとして追加。
      flash[:notice] = 'Book was successfully created.'
      # 「転送したいアクションへのURL」をbook_path(book.id)に指定する事でshowアクションが働き、show.html.erbを探し出してそこへ遷移する。
      # book_pathの「book」はshowアクションの名前付きルートの名称で、def show(showアクション)の処理を行ってくれる。
      redirect_to book_path(@book.id)
    else
      # render…アクション名。同じコントローラ内の別アクションのviewを表示出来る。
      # renderは直接ビューファイルを表示させている。 そのため画面の遷移はなく、表示されているHTMLが入れ替わるのみ。
      # renderとredirect_toの違いについては「アプリケーションを完成させよう 9章」参照。
      # 大きな違いとして、renderは「アクションを新たに実行しない」、redirect_toは「アクションを新たに実行する」という違いがある。
      @books = Book.all
      render :index # newからindexに変更する際は、renderの直前に「@books = Book.all」を設定すること。理由は以下の通り。
      # renderは直接viewファイルを表示するので、「そのviewファイルに必要なインスタンス変数」は、予めrenderの前に用意する必要があるから。
      # バリデーション実装に伴うアクションの処理変更の際は、エラー発生の場合の処理として、renderとその遷移先で必要となる変数の定義を必ずする事。
      # ただし、エラー情報を持った変数についてはノータッチ。誤って再定義し直してエラー情報を上書きしないようにする事。
      # 上記のrender :newの部分でredirect_toを使うとnewアクション内で再度@book = Book.newが実行されるため、
      # @bookが上書きされてエラーメッセージが消えてしまう。基本的に、エラーメッセージを扱う際はrender、それ以外はredirect_toを使うと覚えること。
    end
  end

  def index
    # モデルの情報をform_withに渡す。
    # このnewはこのコントローラに定義されてるnewアクションの事ではなく、allと同じでモデルに備わってる持つメソッド機能の一つ。
    @book = Book.new
    # allメソッドは、そのモデルがやり取りしているDBのテーブル(booksテーブル)に保存されている全てのデータを取得する。
    @books = Book.all
  end

  def show
    # findメソッドは引数を受け取り、idカラムを引数と比べてレコードを取得してくるメソッド。
    # 取得したデータ1つをインスタンス変数に格納し、そのインスタンス変数をviewファイルで利用して詳細画面を表示する。
    # リンクの設定はビューファイル内にlink_toメソッドを用いる事で設定する。
    @book = Book.find(params[:id])
  end

  def edit
    # 投稿済みのデータを編集するため、保存されているデータをfindメソッドを用いて取得する
    @book = Book.find(params[:id])
  end

  # 最初、renderの直前に「@book = Book.find(params[:id])」と記述してしまったせいで、エラー情報を持った変数を上書きしてしまっていた。
  def update
    # 投稿済みのデータを編集するため、保存されているデータをfindメソッドを用いて取得する
    @book = Book.find(params[:id])
    # book_paramsメソッドを用いてフォームから入力されたデータを受け取り、updateメソッドで既存の投稿内容を更新。
    # バリデーションの結果を、コントローラで検出できるようにする。(if文を用いる)
    # book.rb(モデルファイル)にバリデーションチェックを設定しているため、updateメソッドが走った際、trueかfalseが返ってくる。
    # 対象のカラムにデータが入力されていた場合はtrueが返ってくる。この場合、次に表示したいページにリダイレクトさせる。
    # 対象のカラムにデータが入力されていなかった場合はfalseが返ってくる。この場合、編集ページを再表示させる。
    if @book.update(book_params) # ここでユーザーが入力した内容を受け取ってる。(空かどうかもここで確認してる)
      # 更新に成功した場合の処理。(フラッシュメッセージが表示される)
      # flashオブジェクトのキーである[:notice]に表示したいメッセージをvalueとして追加。
      flash[:notice] = 'Book was successfully updated.'
      # 「更新成功」のメッセージ表示と共に詳細画面(show.html.erb)へ画面遷移。
      # 「転送したいアクションへのURL→book_path(book.id)を指定」する事で、 showアクション、show.html.erb(詳細画面)へリダイレクトする。
      redirect_to book_path(@book.id)
    else
      # 更新に失敗した場合の処理(エラーメッセージが表示される)。エラー情報を持つ変数@bookについてはノータッチ。誤って再定義しないように。
      render :edit
    end
  end

  # ビュー側で実装する「削除」ボタンをクリックすると、削除リストのid付きでURLが送信される。
  # 送られてきた削除idを元にレコードが探され、そのレコードを削除する。
  def destroy
    book = Book.find(params[:id])  # データ（レコード）を1件取得。
    book.destroy  # データ（レコード）を削除
    redirect_to '/books'  # 投稿一覧画面へリダイレクト
  end

  # private…一種の境界線。「ここから下のコードは、このcontroller(books_controller.rb)の中でしか呼び出せません」という意味。(×他ファイル)
  private
  # ストロングパラメータというフォームから入力されたデータを受け取る仕組み(「アプリケーションを完成させよう」2章の後半参照)。脆弱性対策。
  # モデル名_params…メソッド名。(今回はbook_params)このメソッドをここに書く理由については、2章の後半(メソッドの呼び出しに制限をかける)参照。
  # ーーーーーーーーーーーーparams…フォームから送られてくるデータが入っている。ーーーーーーーーーーーー
  # require…送られてきたデータの中からモデル名(ここでは:book)を指定し、データを絞り込む。(モデル名での絞り込みであってtitleやbodyといったカラムの指定、絞り込みはしてない)
  # permit…require(モデル名の条件)で絞り込んだデータの中から、取得や保存を許可するカラムを指定する。
  # requireやpermitでモデル名やカラムの指定、絞り込みをするのは、「悪意あるユーザーが改竄したデータを保存しないようにする」為。
  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<!--errors…モデルにバリデーションをかけた時に、発生したエラーの内容を確認出来るメソッド。
any? と組み合わせることで、エラーが発生しているかどうかを判定出来る。
また、full_messagesと組み合わせることで、エラーの内容を出力出来る。 (この時、エラー文は配列で保存されているため、eachを使う)-->
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li> <!--ここで配列|message|から取り出した、該当のエラーメッセージを出力している-->
    <% end %>
  </ul>
<% end %>

<!--form_with…viewファイルで使用することが出来る、フォームの作成に用いられるメソッド。-->
<!--|f|の部分はブロック変数と言い、特定の範囲内で使える変数のこと。今回だとform_withのdoからendまでの範囲で使える。-->
<!--このブロック変数「f」には設定したmodelの情報(今回であればBook.new or @book)も含まれている-->
<%= form_with model: @book, url: update_book_path, method: :patch do |f| %>
  <!--「:title」の部分にはプロパティが入ることになり、ブロック変数「f」にはBookモデルの情報も入っているため、
  このプロパティ名をtitleとすることで、BookモデルにあるtitleカラムだとRailsは判別することができ、DBに保存することが出来る-->
  <!--ヘルパー(モデルオブジェクト)「text_field」は単一行のテキストフィールドを提供する部品-->
  <!--「f.text_field」「f.text_area」「f.submit」の「f」はブロック変数「f」のことだよー　byメンター-->
  <div class="field">
    <label for="book_title">Title</label>
    <div class="book_title">
      <%= f.text_field :title %>
    </div>
  </div>

  <div class="field">
    <label for="book_body">Body</label>
    <div class="book_body">
      <!--ヘルパー(モデルオブジェクト)「text_area」は複数行のテキストフィールドを提供する部品-->
      <%= f.text_area :body %>
    </div>
  </div>

  <!--わざわざ<div class="actions"></div>でクラス名をつける必要はない-->
  <%= f.submit 'Update Book', class: "actions" %>
<% end %>

<!--名前付きルートには""はいらない-->
<%= link_to "Show", book_path(@book.id) %>

|

<!--最初、/booksの部分に""をつけていなかったせいで、画面遷移時、エラーが発生した-->
<%= link_to "Back", "/books" %>

app/views/books/index.html.erb
<!--最初、<form class="new_book"></form>をform_withとセットで使ってしまい、入力フォームを二重に作ってしまっていたせいでバグが起きていた-->

<h1>Books</h1>

<!--<tr>：「table row」の略で表の行部分（横方向）を指定するタグ。
<tr>～</tr>で表の横部分を指定し、その中に<th>～</th>や<td>～</td>で表題や縦軸を指定-->
<!--th要素のcolspan属性は、表(テーブル)における、水平方向の見出しセルの結合数（セルがまたがる列数）を指定する属性-->
<!--<thead>タグって必要？-->
<table>

  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <!--eachメソッドは、配列やハッシュがもつ要素を順番に取得して処理を実行する-->
    <!--@books.eachと記述することで、Bookレコードの数だけ繰り返し処理を行う。各レコードの内容はbookという変数に格納される-->
    <% @books.each do |book| %>
      <!--書式は、「link_to 表示させるテキスト , リンク先URL [,オプション]」　※今回、オプションは設定しない-->
      <!--名前付きルートになったので、リンク先URLの部分は"/books/#{book.id}"からbook_path(book.id)に変更している-->
      <tr>
        <td><%= book.title %></td>
        <td><%= book.body %></td>
        <td>
          <%= link_to "Show", book_path(book.id) %>
        </td>
        <td>
          <%= link_to "Edit", edit_book_path(book.id) %>
        </td>
        <td>
          <%= link_to "Destroy", destroy_book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %>
        </td>
      </tr>
    <% end %>

    <!--上記のrubyのeachメソッドでは一つ一つデータを取り出して、以下のようなHTMLに変換してviewで表示している-->
    <!--<tr>-->
    <!--  <td>リーダブルコード</td>-->
    <!--  <td>より良いコードを書くためのシンプルで実践的なテクニック</td>-->
    <!--  <td>-->
    <!--    <a class="show_54070" href="/books/54070">Show</a>-->
    <!--  </td>-->
    <!--  <td>-->
    <!--    <a class="edit_54070" href="/books/54070/edit">Edit</a>-->
    <!--  </td>-->
    <!--  <td>-->
    <!--    <a data-confirm="Are you sure?" class="destroy_54070" rel="nofollow" data-method="delete" href="/books/54070">Destroy</a>-->
    <!--  </td>-->
    <!--</tr>-->

  </tbody>

</table>

<h2>New book</h2>

<!--errors…モデルにバリデーションをかけた時に、発生したエラーの内容を確認出来るメソッド。
any? と組み合わせることで、エラーが発生しているかどうかを判定出来る。
また、full_messagesと組み合わせることで、エラーの内容を出力出来る。 (この時、エラー文は配列で保存されているため、eachを使う)-->
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li> <!--ここで配列|message|から取り出した、該当のエラーメッセージを出力している-->
    <% end %>
  </ul>
<% end %>

<!--form_with…viewファイルで使用することが出来る、フォームの作成に用いられるメソッド。-->
<!--|f|の部分はブロック変数と言い、特定の範囲内で使える変数のこと。今回だとform_withのdoからendまでの範囲で使える。-->
<!--このブロック変数「f」には設定したmodelの情報(今回であればBook.new or @book)も含まれている-->
<%= form_with model: @book, url: '/books', method: :post do |f| %>
  <!--「:title」の部分にはプロパティが入ることになり、ブロック変数「f」にはBookモデルの情報も入っているため、
  このプロパティ名をtitleとすることで、BookモデルにあるtitleカラムだとRailsは判別することができ、DBに保存することが出来る-->
  <!--ヘルパー(モデルオブジェクト)「text_field」は単一行のテキストフィールドを提供する部品-->
  <!--「f.text_field」「f.text_area」「f.submit」の「f」はブロック変数「f」のことだよー　byメンター-->
  <div class="field">
    <label for="book_title">Title</label>
    <div class="book_title">
      <%= f.text_field :title %>
    </div>
  </div>

  <div class="field">
    <label for="book_body">Body</label>
    <div class="book_body">
      <!--ヘルパー(モデルオブジェクト)「text_area」は複数行のテキストフィールドを提供する部品-->
      <%= f.text_area :body %>
    </div>
  </div>

  <!--わざわざ<div class="actions"></div>でクラス名をつける必要はない-->
    <%= f.submit 'Create Book', class: "actions" %>

<% end %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Title</h2>
<p><%= @book.title %></p>

<h2>Body</h2>
<p><%= @book.body %></p>

<!--名前付きルートには""はいらない-->
<%= link_to "Edit", edit_book_path(@book.id) %>

<!--最初、/booksの部分に""をつけていなかったせいで、画面遷移時、エラーが発生した-->
<%= link_to "Back", "/books" %>

app/views/homes/top.html.erb
<h1>
  ようこそ
  <strong>BOOKERS</strong>
  へ！
</h1>

<p>
  <strong>Bookers</strong>
  では、さまざまな書籍に関するあなたの意見や
</p>

<p>
  印象を共有し交換することができます
</p>

<p>
  <a href="/books">start</a>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--「= yield」にて他のviewファイル(index.htmlとか)が読み込まれ、そのviewファイルの内容が画面に表示される。
    <!--今回は画面の上部にflashメッセージを表示させたいので、「= yield」の前(他のviewファイルを読み込む前)にflashメッセージを実装している-->
    <!--.notifications <!--flashメッセージの親要素となるdivタグを定義-->
    <!--  - flash.each do |key, value| <!--flashオブジェクトの呼び出し。投稿成功の場合は、keyに"notice"、valueに"メッセージが送信されました"が入る-->
        <!--content_tagを使用してflashメッセージを表示させるためのdivタグを作成。前述の通り、keyに"notice"、valueに"メッセージが送信されました"が
    <!--    入っているため、class名が"notice"、表示させる内容が"メッセージが送信されました"となる-->
        <!--content_tagはHTMLタグを生成するメソッドで、以下のように使う。
    <!--    content_tag(作成するタグの種類, 表示したい内容, class等のオプション)-->
    <!--    = content_tag(:div, value, class: key)-->
    <%= yield %>
  </body>
</html>